### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by rubenwardy** [pruttned/owl-bt#19]
I've been playing around with this editor. Thanks for this!

Here is some feedback.

**Main Criticism**

* ~~Doesn't appear to be any way to copy/move nodes and subtrees. This should be possible using both standard keyboard shortcuts and mouse.~~
* No way to change root node type
* Disallow loading owl-bt.json file as a tree. I got confused between projects and trees
* The way file loading and stuff was confusing to begin with - maybe only require users to open owlbt with a project dir, and allow creating tree files from within the web UI
* Update font awesome, the first icon I found - `running` wasn't available in this editor

**Minor suggestions**

* Nodes with no description don't align properly
  
   ![image](https://user-images.githubusercontent.com/2122943/75631263-53d1fe00-5be9-11ea-8fda-db2dffa9420c.png)
* Split programmatic name and readable (ie: shown) labels for nodes. Ability to comment / give custom labels. 
* Logically, shouldn't decorators be above a node because they run before the node? They are like this in unreal

  ![image](https://user-images.githubusercontent.com/2122943/75631356-128e1e00-5bea-11ea-9129-29cb5f3e5752.png)

* Minor thing - when adding new nodes, maybe move camera with/relative to the parent to avoid this:
  
  ![image](https://user-images.githubusercontent.com/2122943/75618355-d95f9a80-5b64-11ea-8300-79b548c67bb6.png)

  Ie: if the parent node moves 10 pixels, move the camera 10 pixels

**The good stuff**

* It looks and feels great
* owl-bt.json is a nice way to define nodes

**Comment by rubenwardy** [comment]
I've just discovered copy and paste, and shift-right and left

**Comment by rubenwardy** [comment]
Updated first post. Note - please don't take this as demanding! If I decide to use/adapt this tool, I'll probably end up contributing a lot of that stuff. I'd appreciate your feedback and whether you are still working on this (I see your forum topic on tigsource is still active as of Jan 2020)

**Comment by pruttned** [comment]
Hi, thanks for you feedback. 
although I did not make any changes to owl-bt recently, I'm actively using it for developing my game. So it is still alive.

- "No way to change root node type" - yeah I would like to add support for changing type of any node in the future.
- "The way file loading and stuff was confusing to begin with - maybe only require users to open owlbt with a project dir, and allow creating tree files from within the web UI" - yes this is also something that I would like to implement in the future.
- "Split programmatic name and readable (ie: shown) labels for nodes" - that's a good idea. I would go with the optional label/comment.
- "Logically, shouldn't decorators be above a node because they run before the node?" - I was thinking in the start to do it as in Unreal, but in my personal opinion, it looked horrible. Therefore I decided to do it like this. 

Currently I don't have much free time to work actively on owl-bt, but I would gladly accept any PRs.

Could you pls separate this issue into multiple issues, each with a single item? It will be easier to track individual items that way - so I'm closing this one issue for now.
Thx
